---
# tasks file for packages
- name: Add new repositories keys
  apt_key:
    url: "{{item.key}}"
  with_items: "{{ k8s_common_add_packages_keys }}"
  register: aptnewkeys

- name: Add new repositories to sources
  apt_repository:
    repo: "{{item.repo}}"
  with_items: "{{ k8s_common_add_packages_repositories }}"

- name: Force update cache if new keys added
  set_fact:
        linux_add_packages_cache_valid_time: 0
  when: aptnewkeys.changed

- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ k8s_add_packages_cache_valid_time }}"
  with_items: "{{ k8s_common_add_packages_names }}"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add k8s_common_admin_user user to docker group
  user: 
    name: "{{ k8s_node_admin_user }}"
    shell: /bin/bash
    group: docker

- name: Check that docker service is started
  service: 
    name: docker 
    state: started

- name: Add fix gateway init.d script
  template:
    src: etc/rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: '0755'